apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: argocd # 적절한 네임스페이스를 사용하세요
type: Opaque
data:
  mysql-username: ZG9uZ2p1bg==
  mysql-password: Q2hvaTg5MjEh
  smtp-username: Y2RvbmdqdW4wODMwQGdtYWlsLmNvbQ==
  smtp-password: eG9tdyBkdnF2IGJkeXcgaHV2cA==
  etherscan.api.key: NEVLVlUxWjFaWDI3RlBBRURNNUJKSkRJUjEyVkpHVENJSg==
  etherscan.contract.address: MHhFNTY0QmQ2MjRiMzdDOGE5MUU0MEMwZkJiOUQ5YTQwNThkN0Y2OTgx
  metamask.private.key: Y2RhM2QxNTgxYjBjZjE2YzQ1ZjUyMjU1OTQ5NDhiYmQ1MDY2NGY5YmYyMjZlODhjNDNiODQwODYzY2IwMzE5ZQ==
